Spellcheck spans
PolicyStat/ckeditor-spell-check-plugin-js-dev-edge pull request #16
Opened 2016-09-16 14:43 UTC by sbaughman

2016-09-16 14:49 UTC, caffodian commented on plugins/nanospell/plugin.js
> -		},
I'm surprised that this could go away.  Then I noticed that in scanWords, we duplicate this functionality.

2016-09-16 14:52 UTC, caffodian commented on plugins/nanospell/plugin.js
> -		},
I think I'd rather keep this method and then have scanWords call it instead.  Mostly for clarity reasons, and also, I suspect that in the future, we may have some cases where we'll want to be smarter about doing element checking vs. actual range checking.  (For example, copy/paste or drag and drop, which don't happen as often, but we haven't really thought about at all)

2016-09-16 14:54 UTC, caffodian commented on plugins/nanospell/plugin.js
> -		},
Ah yes.  I noticed this function was dead code as well, after the previous thing.

2016-09-16 14:55 UTC, caffodian reviewed
looks good to me, pending test revisions

2016-09-16 19:53 UTC, caffodian commented on plugins/nanospell/plugin.js
> +			editor.on(EVENT_NAMES.START_CHECK_WORDS, checkWords, self);
curious why you moved these.  Not opposed.  I was floating between these two options for a while.

2016-09-16 20:02 UTC, sbaughman commented on plugins/nanospell/plugin.js
> +			editor.on(EVENT_NAMES.START_CHECK_WORDS, checkWords, self);
Just seemed to make sense to have all the event listener setup together.  I also like the pattern of making a `setupEventListeners` function to group them together and calling that from `init`

2016-09-19 14:03 UTC, caffodian commented on plugins/nanospell/plugin.js
> +					node.is('br') || node.is('sup') || node.is('sub'))) {
we can actually do

`node.is('br', 'sup', 'sub')`

at least this is what http://docs.ckeditor.com/#!/api/CKEDITOR.dom.element-method-is would indicate.

2016-09-19 14:06 UTC, caffodian requested changes
Could we also add a simple walking test, maybe something like

`<p>sometext<br/>something<sup>superscript</sup> anotherthing<sub>subscript</sub>` ?

The change looks simple, but it would be good for future regressions.  Looks good though!

2016-09-19 18:37 UTC, caffodian approved these changes

2016-09-19 20:02 UTC, merged